# Generated by Django 5.2.14 on 2026-05-21 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(unique=True)),
                ("solar_kw", models.FloatField()),
                ("load_kw", models.FloatField()),
                ("grid_price_eur_per_kwh", models.FloatField()),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DispatchInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("charge", "Charge"),
                            ("discharge", "Discharge"),
                            ("idle", "Idle"),
                        ],
                        max_length=16,
                    ),
                ),
                ("soc_kwh", models.FloatField()),
                (
                    "battery_power_kw",
                    models.FloatField(
                        help_text="Positive when discharging, negative when charging."
                    ),
                ),
                ("solar_to_load_kwh", models.FloatField()),
                ("solar_to_battery_kwh", models.FloatField()),
                ("battery_to_load_kwh", models.FloatField()),
                ("grid_to_load_kwh", models.FloatField()),
                ("curtailed_solar_kwh", models.FloatField()),
                (
                    "interval",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch",
                        to="energy.energyinterval",
                    ),
                ),
            ],
            options={
                "ordering": ["interval__timestamp"],
            },
        ),
    ]
